### PR TITLE
Add iPhone 7 info

### PR DESCRIPTION
**Pull request by alonalon**
Add missing info about iPhone 7 & iPhone 7 plus

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Did you add this by hand? If yes, use the `make.js` script in this repository.

```
$ node make.js
```

**Comment by kevva** [comment]
I just tried to run it myself, but it didn't add iPhone 7 for some reason. Seems like it hasn't been added to viewportsizes.com/devices.json.

**Comment by SamVerschueren** [comment]
Odd, how is that list maintained? Doesn't seem like we could do a PR somewhere... Maybe we should ping the developer on Twitter [Matt Snow](https://twitter.com/stowball)?

The question is, how well is that list being maintained? Does it add other extra devices after running the make file?

**Comment by kevva** [comment]
@SamVerschueren, nope. I guess we could add it here http://viewportsizes.com/add/.

**Comment by SamVerschueren** [comment]
> It's somewhat worrying though that no devices has been added in a long time.

Absolutely!

Can't seem to find another decent source though. So I believe we can do two things here.

1. Add the device to http://viewportsizes.com/add/
2. Create a second JSON file with custom devices and merge that one in the makefile. This way we can accept PRs for devices not on the list, and still retrieve the data from that website.

**Comment by alonalon** [comment]
Ah sorry missed make.js! looked at viewportsizes.com and as you guys said, no info about iPhone 7, nor is Samsung Galaxy s7 added there either, so maybe a second JSON file would be a good idea!

**Comment by kevva** [comment]
@SamVerschueren, the second alternative seems better to me. That way we don't need to rely on someone not responding or whatever.

**Comment by SamVerschueren** [comment]
@kevva Jep, 2 was my preference of choice as well. Let's do that.

@alonalon Care to transform this PR into the suggested solution?

**Comment by alonalon** [comment]
@SamVerschueren sure, I think I have some time over, otherwise I ping you here!

**Comment by SamVerschueren** [comment]
Alright, thanks @alonalon!

**Comment by alonalon** [comment]
@SamVerschueren sorry for late notice, but I don't think I have time to solve this :(

**Comment by SamVerschueren** [comment]
@alonalon No problem.

I created issue #8 to track that new feature. Let's close this one and continue the discussion/remarks in that issue instead.

**Pull request closed without merging**
